### ISSUE TITLE
Watermarking assumes trigger set stored locally but not on Github

### ISSUE THREAD

**Issue by asim29** [ssg-research/amulet#27]
https://github.com/ssg-research/amulet/blob/7d52639793bc033816ea8166ea6de23a37a5e434/examples/defense_pipelines/run_watermark.py#L35C1-L37C6

The current watermarking code assumes that the trigger set is stored locally. We need one of the following:
1. A script/function to download the trigger set when the Watermarking module is called.
2. A directory where the trigger set can be stored as part of the library.
3. Generate the trigger set on the fly.

**Comment by sebszyller** [comment]
Example watermark added; users should provide their own otherwise.
